---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: installedfeatures.k8s.kaiserpfalz-edv.de
spec:
  group: k8s.kaiserpfalz-edv.de
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Cluster
  names:
    kind: InstalledFeature
    singular: installedfeature
    plural: installedfeatures
    shortNames:
    - ift
    - ifts
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          group:
            type: string
            default: 'unspecified'
          image:
            type: string
            pattern: '^[0-9a-zA-Z=]+$'
          version:
            type: string
            pattern: '^\d+(.\d+)?(.\d+)?(.\d+)?(-[-a-z0-9]+)?$'
            default: '1.0.0'
          shortDescription:
            type: string
          provider:
            type: string
            default: 'unspecified'
          url:
            type: string
          relations:
            type: object
            requires:
              type: string
            suggests:
              type: string
            conflicts:
              type: string
            provides:
              type: string
            breaks:
              type: string

  additionalPrinterColumns:
    - JSONPath: .spec.group
      name: Group
      type: string
    - JSONPath: .spec.version
      name: Version
      type: string
    - JSONPath: .metadata.creationTimestamp
      name: Age
      type: date
    - JSONPath: .spec.url
      name: Documentation
      type: string
