# permissions for end users to view installedfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installedfeature-viewer-role
rules:
- apiGroups:
  - features.kaiserpfalz-edv.de
  resources:
  - installedfeatures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - features.kaiserpfalz-edv.de
  resources:
  - installedfeatures/status
  verbs:
  - get
