# permissions for end users to edit installedfeatures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installedfeature-editor-role
rules:
- apiGroups:
  - features.kaiserpfalz-edv.de
  resources:
  - installedfeatures
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - features.kaiserpfalz-edv.de
  resources:
  - installedfeatures/status
  verbs:
  - get
