# permissions for end users to view installedfeaturegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: installedfeaturegroup-viewer-role
rules:
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeaturegroups
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeaturegroups/status
    verbs:
      - get
