
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeaturegroups
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeaturegroups/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeatures
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - features.kaiserpfalz-edv.de
    resources:
      - installedfeatures/status
    verbs:
      - get
      - patch
      - update
