apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: k8s-installed-features-catalogue.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: { }
  customresourcedefinitions:
    owned:
      - description: InstalledFeature is the Schema for the installedfeatures API
        displayName: Installed Feature
        kind: InstalledFeature
        name: installedfeatures.features.kaiserpfalz-edv.de
        version: v1alpha1
  description: The operator manages the dependencies of the InstalledFeatures
  displayName: InstalledFeatureOperator
  icon:
    - base64data: ""
      mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - information
  links:
    - name: K8s Installed Features Catalogue
      url: https://k8s-installed-features-catalogue.domain
  maintainers:
    - email: rlichti@kaiserpfalz-edv.de
      name: Roland T. Lichti
  maturity: alpha
  provider:
    name: Kaiserpfalz EDV-Service, Roland T. Lichti
    url: https://www.kaiserpfalz-edv.de
  version: 0.0.0
