---
kind: InstalledFeature
apiVersion: features.kaiserpfalz-edv.de/v1alpha1
metadata:
  name: k8s-feature-library-operator
spec:
  kind: k8s-feature-library-operator
  group: cluster-info
  version: 1.0.0-alpha1
  provider: Kaiserpfalz EDV-Service, Roland T. Lichti
  description: |+
    The k8s-feature-operator checks if all dependencies and conflicts are solved for a given k8s-feature-library CR.
  uri: https://www.kaiserpfalz-edv.de/k8s/k8s-installed-features-catalogue/
  depends:
    - kind: k8s-feature-library
      group: cluster-info
      min-version: 1.0.0
      max-version: 2.0.0
  conflicts:
    - kind: k8s-feature-operator
      group: cluster-info
      min-version: 2.0.0